# Generated by Django 5.2.7 on 2025-11-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_user_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nome_ajustado', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('INDUSTRIA', 'Industria'), ('DISTRIBUIDOR', 'Distribuidor')], max_length=100)),
                ('cnpj', models.CharField(max_length=20)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('razao_social', models.CharField(max_length=255)),
                ('gestor', models.CharField(max_length=255)),
                ('telefone_gestor', models.CharField(max_length=20)),
                ('email_gestor', models.EmailField(max_length=255, unique=True)),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('senha_definida', models.BooleanField(default=False)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
